- name: run a test copy
  hosts: local
  become: yes    #Give sudo priviledge

  tasks:
    - name: Copy file for testing
      copy:
        src: /home/tomiwa_7/proj-app/test.txt
        dest: /home/tomiwa_7/test.txt
        state: present
biubdod[vf[oub[jd fdsoujvb osdjv [o'a[doods ovdovus o 
