- name: Infastructure Service Setup
  hosts: local
  become: yes    #Give sudo priviledge
  collections:
    - community.docker
  vars:
    prometheus_version: 3.9.1

  tasks:
    - name: update package manager        # Always Update package manager
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
       name: "{{ item }}"
       state: present            # Present Version Change to "latest" for latest version
      loop:
         - apt-transport-https
         - ca-certificates
         - curl
         - software-properties-common

# -------------------Docker Installation-------------

    - name: Install Docker
      apt:
        name:
         - docker.io
         - docker-compose-plugin
        state: present
        update_cache: yes

# -----------------------Install grafana------------------

    - name: Install grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Ensure grafana service running
      service:
         name: grafana-server
         state: started
         enabled: yes

# ----------------------Install Prometheus------------------
#
#    - name: Downlaod prometheus tarball
#      get_url:
#        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
#        dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
#
#    - name: Extract prometheus tarball
#      unarchive:
#          src: "prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
#          dest: /opt/
#          remote_src: yes
#
#    - name: Create symlink for prmetheus binary
#      file:
#        src: "prometheus-{{prometheus_version}}.linux-amd64/prometheus"
#        dest: "/usr/local/bin/prometheus"
#        state: link


    - name: Create prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Monitoring
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \\
            --config.file=/etc/prometheus/prometheus.yml \\
            --storage.tsdb.path=/var/lib/prometheus \\
            --web.console.libraries=/etc/prometheus/console_libraries \\
            --web.console.templates=/etc/prometheus/consoles

          [Install]
          WantedBy=multi-user.target


    - name: Reload system
      command: systemctl daemon-reload

    - name: check if Prometheus Service is running
      service:
       name: prometheus
       state: started
       enabled: yes

#----------------------Install Node Exporter------------------

#    - name: Install node_exporter
#      apt:
#        name: prometheus-node-exporter
#        state: present
#        update_cache: yes

    - name: Ensure node_exporter is running
      service:
        name: node_exporter
        state: started
        enabled: yes

 #----------------------  Configurations ----------------------------

       # ------Write Dockerfile-------
    - name: Create Dockerfile
      copy:
          dest: /mnt/app/Dockerfile
          content: |
             # States the Base Image
             FROM python:3.10-slim

             # Set Working Dir (Where the source code will be copied)
             WORKDIR /app
             # Copy the Files
             COPY requirements.txt ./
             # Install Dependencies
             RUN pip install --no-cache-dir -r requirements.txt
             RUN mkdir -p /app/pers_storage
             # Copy the rest of the app
             COPY app.py templates/index.html static/style.css static/script.js /app/
             # Expose the port
             EXPOSE 5000
             # Run the app 
             CMD ["python", "app.py"]

       # ------  Write Compose--------------

    - name: Create Compose
      template:
        src: "/mnt/app/ansible-proj/docker-compose.yml.j2"
        dest: "/mnt/app/docker-compose.yml"
        mode: 0644
#-------Start docker container---------------------


    - name: Ensure docker installed
      apt:
         name:
          - docker.io
          - docker-compose-plugin
         state: present
         update_cache: yes

    - name: Ensure Docker service is running
      service:
         name: docker
         state: started
         enabled: yes

    - name: Start Docker Container
      community.docker.docker_compose_v2:
        project_src: /mnt/app/
        state: present

